Copyright © 2025 Giovanni Squillero / Politecnico di Torino  
https://github.com/squillero/programmer-zendo  
Free under certain conditions — see the license for details 

In [1]:
from itertools import accumulate
from icecream import ic
import numpy as np
from tqdm.auto import tqdm
from matplotlib import pyplot as plt

# 0-1 Multiple Knapsack Problem

see: [https://en.wikipedia.org/wiki/Knapsack_problem](https://en.wikipedia.org/wiki/Knapsack_problem)

In [2]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [3]:
NUM_ITEMS = 10
DIMENSIONS = 5
MAX_STEPS = 20_000

WEIGHTS = np.random.randint(1, 50 + 1, size=(NUM_ITEMS, DIMENSIONS))
MAX_WEIGHTS = np.full(DIMENSIONS, NUM_ITEMS * 20)
VALUES = np.random.randint(1, 100 + 1, size=NUM_ITEMS)

In [4]:
def evaluate(knapsack):
    if all(np.sum(WEIGHTS[knapsack], axis=0) < MAX_WEIGHTS):
        return np.sum(VALUES[knapsack])
    else:
        return -1

In [5]:
WEIGHTS

array([[39, 29, 15, 43,  8],
       [21, 39, 19, 23, 11],
       [11, 24, 36, 40, 24],
       [ 3, 22,  2, 24, 44],
       [30, 38,  2, 21, 33],
       [12, 22, 44, 25, 49],
       [27, 42, 28, 16, 15],
       [47, 44,  3, 37,  7],
       [21,  9, 39, 18,  4],
       [25, 14, 50,  9, 26]])

In [6]:
MAX_WEIGHTS

array([200, 200, 200, 200, 200])

In [7]:
VALUES

array([53,  2, 84, 92, 60, 71, 44,  8, 47, 35])

In [8]:
solution = np.array([True, True, True, False, False, True, True, True, False, False])
evaluate(solution)

-1

In [9]:
solution

array([ True,  True,  True, False, False,  True,  True,  True, False,
       False])